### ISSUE TITLE
Ranking comparison page - UI changes

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#104]
<img width="1152" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/5492b19d-1486-41dc-98ee-5307a5d007a3">

## Tasks

- [x] Remove `Single project` from project card as there are no more composite projects
- [x] Replace `Quick view` with `Details` and eye icon
- [x] Header question: `Which of these projects has had a greater impact on Optimism?`
- [x] Remove explanation from Abstain card - Decline to cote
- [x] Change footer to include only category name, remove `Evaluating`
- [x] More clear states on `Finish` button
  * Before ranking threshold met: Disabled button, lock icon, number signals how many are left
  * After ranking threshold met: Button not disabled, arrow icon
