### ISSUE TITLE
Project details popup - UI changes

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#105]
<img width="533" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/513aa56a-90dc-4960-b6f6-37e7a7689490">

## Tasks

- [x] Remove `Single project` label, no longer used
- [x] Add project link under project image (target=_blank)
- [x] Better layout of content section:
  * Respect linebreaks
  * Include both contributionDescription and impactDescription
  * Overflow / scroll bar for long content
