### ISSUE TITLE
Create list popup - UI changes

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#107]
<img width="536" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/6eb1033d-e2a2-484b-ab73-c34f9368cf7b">

## Tasks

- [x] Add header `Create list`
- [x] Popup needs some new design @mosaeedi 
- [x] Add texts with links 
- [ ] Change button states based on progress

**Comment by mosaeedi** [comment]
<img width="1324" alt="Screenshot 2023-11-01 at 6 55 22 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/2652aab9-da6a-4c2b-85f2-4807f4b8e785">

[Link to Figma](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2560-16278&mode=design&t=gmHa1SilRYDR7FGJ-4)

**Comment by kristoferlund** [comment]
Looks good! Clear and clean.

**Comment by kristoferlund** [comment]
We need to make some additional changes to UI and flow. 

## 1. Naming lists

Add a text field to list creation dialog

## 2. Replace old list if creating new

Flow:
  1. Warn user: “Creating a new list will overwrite existing”
  2. Revoke old list attestation
  3. Create new list attestation

## 3. Use another UID when referencing projects and individuals in lists.

Lists should not reference the `application UID` of a project or an individual but a new `approved application UID`, [EAS schema #146](https://optimism.easscan.org/schema/view/0xebbf697d5d3ca4b53579917ffc3597fb8d1a85b8c6ca10ec10039709903b9277). 

How do we find this id? 

Example for Metagov:
1. Take `applicantAddress` from project
2. Look up `applicantAddress` on the EAS GQL api, finding the first attestation for that address with schema 146
3. Use that UID when referencing project in list: 0xe367584886bdb185038a466f6a8e5a4ad746ffef051507a311cae85ae11c7d5e

<img width="701" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/e96d2019-946a-471b-9451-6a11f107637d">

@mosaeedi we need your help to adjust the popup UI accordingly..

**Comment by mosaeedi** [comment]
1. When users create the list before, should we allow them to create a new list?
2. If they enter a new name, will that still replace the old list?

**Comment by mosaeedi** [comment]
@kristoferlund 

1. When users create the list before, should we allow them to create a new list?
2. If they enter a new name, will that still replace the old list?

**Comment by mosaeedi** [comment]
From UX perspective, it's better to break this modal into two steps!
First, we can tell the user what this is about, and then in the second modal, we can let user enter a name and handle all errors and warnings.
But if it means more work on dev side, please let me know.

**Comment by kristoferlund** [comment]
@mosaeedi 
Requirements changed slightly. We will not allow users to name lists. Only thing needed is warning message if list has been created before.

**Comment by mosaeedi** [comment]
I've updated the Figma, please take a look.
Note: Since we have a small warning at the bottom, it's better to show this error message on the top to make sure user won't miss it.

[**Figma link**](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2701-8064&mode=design&t=P7I2B60GsnFiCrFq-4)

<img width="916" alt="Screenshot 2023-11-06 at 4 42 46 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/7a2ddfa9-2585-4a3a-9c63-93ec1f4add7c">
