### ISSUE TITLE
Ranking overview / edit page -  UI changes

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#108]
<img width="559" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/509d10c9-1b36-4ef2-8af7-603e93bbe1b4">

## Tasks
- [ ] New header: `Ranking`
- [ ] Change button text: `Edit`
- [ ] Add status for categories
  * [Not ranked]
  * [Ranked ☑️], [List not created]
  * [Ranked ☑️], [List created]
- [create list] link takes user to ranking confirmation page
- [ ] Switch order on allocation columns 
  * First column: `OP Allocated`
  * Second column: `%`

**Comment by mosaeedi** [comment]
<img width="1150" alt="Screenshot 2023-11-01 at 5 52 28 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/7204823d-b5b2-4600-a019-4b6b93a0465b">

I've changet it a bit to make it easier for user to read and work with.

**Comment by mosaeedi** [comment]
WDYT @kristoferlund @Zeptimus 

[Link to Figma](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2546-15314&mode=design&t=gmHa1SilRYDR7FGJ-4)

**Comment by kristoferlund** [comment]
@mosaeedi Looks nice! I like the popup menu! 

Details:
- Let's use the same terminology all over the app. On this screen that means there are three states only for a category. Also note that states are for categories only. (`Listed` does not have the same meaning as `List created`)
  * [Not ranked]
  * [Ranked ☑️], [List not created]
  * [Ranked ☑️], [List created ☑️]
- We can add another option to popup menu:
  * Details
  * Begin ranking (when state is `Not ranked`)
  * Create lis (when state is `Ranked`)

**Comment by mosaeedi** [comment]
<img width="312" alt="Screenshot 2023-11-02 at 2 12 03 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/0217dead-43a1-49cd-9d09-a841a6144c88">

Fixed the tags.

**Comment by mosaeedi** [comment]
<img width="252" alt="Screenshot 2023-11-02 at 2 12 29 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/ff4dbb8b-5ac3-4483-b8a7-2d17a55c5a85">

I suggest keeping the **Create list** button visible (but disabled) when the project is not ranked yet. this way users from the beginning when they interact with the menu, will know where they can find the Create list button. 
When user ranks it, the button will **get enabled**.

**Comment by mosaeedi** [comment]
<img width="737" alt="Screenshot 2023-11-02 at 2 15 17 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/3e361d0b-44c6-4bd4-9c20-a4e85b6d0f51">

But when the project is ranked and listed, we can hide all other options and show the view details button.

**Comment by mosaeedi** [comment]
Actions dropdown in different states.

<img width="892" alt="Screenshot 2023-11-02 at 2 18 01 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/ac73f1b9-4dd1-429d-8491-084d0359e99d">

**Comment by kristoferlund** [comment]
Looks great! Only thing remaining is new icon for the `Not ranked` state. Pause icon is confusing. Perhaps just no icon?

**Comment by mosaeedi** [comment]
<img width="923" alt="Screenshot 2023-11-02 at 2 32 59 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/467ab2e1-d4d0-4ee2-9ef2-19b51b6a51f3">

Updated the status badges.
I also changed the stroked checkmark icon. The stroked checkmark is a bit overkill!

[**Link to Figma**](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2589-16456&mode=design&t=IEuGdyW4gaDOrhg1-4)
