### ISSUE TITLE
Landing page UI changes

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#99]
## Design changes

<img width="588" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/36054c95-045c-48d8-b28f-e1553776fefc">

<img width="442" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/5173d42b-b4e0-421f-baa0-8c129f74be0e">

## Tasks

- [x] Design new bg images @mosaeedi 
- [ ] Replace bg images in code
- [x] Update text content
- [ ] Replace header logo with new pairwise logo

**Comment by mosaeedi** [comment]
Link to Figma -> [it's here](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2546-10668&mode=design&t=gmHa1SilRYDR7FGJ-4)


[Download asset SVG here.](https://github.com/GeneralMagicio/pw-frontend/files/13227690/Archive.zip)

**Comment by kristoferlund** [comment]
@mosaeedi We should not use the terms `awaiting direction`. Just `Ranked` and `Begin ranking`. 

Also, the pause icon is a confusing match to `Begin ranking`. Perhaps a regular `→` is most clear? After all, `Begin ranking` is a link we want the user to follow.

**Comment by mosaeedi** [comment]
[SVG exports](https://github.com/GeneralMagicio/pw-frontend/files/13237964/Archive.zip)

Updated the assets.

**Comment by yussdev** [comment]
I checked the exported file, We need them as a whole with a circle around them :
![image](https://github.com/GeneralMagicio/pw-frontend/assets/51474231/d5aa1803-ca08-4b08-b342-5642c90dce21)
@kristoferlund @mosaeedi

**Comment by mosaeedi** [comment]
[SVG exports](https://github.com/GeneralMagicio/pw-frontend/files/13238861/Archive.zip)

Please take a look again

**Comment by kristoferlund** [comment]
> [SVG exports](https://github.com/GeneralMagicio/pw-frontend/files/13238861/Archive.zip)
> 
> Please take a look again

@mosaeedi still using wrong term `Awaiting direction`. Should say `Begin ranking`

**Comment by mosaeedi** [comment]
[Ranking-asset.zip](https://github.com/GeneralMagicio/pw-frontend/files/13239652/Ranking-asset.zip)

Sorry! Fixed it.
